config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  devise_for :users
  resources :tweets

  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'all_users' => 'epicenter#all_users'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  # associations
  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # associations
  belongs_to :user
  has_many :tweet_tags
  has_many :tags, through: :tweet_tags
  # validations
  validates :message, presence: true
  validates :message, length: { maximum: 210,
                                too_long: 'Tweets are limited to 210 characters max'
                              }, on: :create
  # callbacks
  before_validation :link_check, on: :create
  after_validation :apply_link, on: :create

  URL_PATTERN = /http(s)?:\/\/.*/

  private

  def apply_link
    arr = self.message.split
    index = arr.map { |x| x.match? URL_PATTERN }.index(true)

    if index
      url = arr[index]
      arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
    end

    self.message = arr.join(" ")
  end

  def link_check
    check = false
    if self.message.include?('http://') || self.message.include?('https://')
      check = true
    end

    if check == true
      arr = self.message.split
      index = arr.map{ |x| x.include? "http"}.index(true)
      self.link = arr[index]

      if arr[index].length > 23
    	  arr[index] = "#{arr[index][0..19]}..."
      end

      self.message = arr.join(" ")
    end
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  # associations
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # associations
  has_many :tweets
  # validations
  validates :username, presence: true, uniqueness: true

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user, only: [:show_user, :following, :followers]

  def feed
    @following_tweets = Tweet.where(user_id: current_user.following.push(current_user.id))
                             .order(created_at: :desc)
  end

  def show_user
  end

  def all_users
    @users = User.all
  end

  def following
    @users = User.where(id: @user.following)
  end

  def followers
    @users = []

    User.all.each do |u|
      @users.push(u) if u.following.include?(@user.id)
    end
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save
    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save
    redirect_to show_user_path(id: params[:id])
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include TweetsHelper

  before_action :authenticate_user!, except: [:index]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)
    get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_tagged(tweet)
    message_arr = tweet.message.split

    message_arr.each_with_index do |word, index|
      if word[0] == '#'
        tag = Tag.find_or_create_by(phrase: word.downcase)
        TweetTag.create(tag_id: tag.id, tweet_id: tweet.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    tweet.message = message_arr.join(' ')
    tweet.save
  end
end

app/views/epicenter/_user.html.erb
<div class="col-md-4">
  <div class="well">

    <h3><%= link_to user.username, show_user_path(id: user.id) %></h3>
    <h4><%= user.name %></h4>
    <p>
      Location: <%= user.location %>
    </p>

    <%= render 'tweets/tweet', tweet: user.tweets.last %>

  </div>
</div>

app/views/epicenter/all_users.html.erb
<h1>All Tweeties</h1>

<div class="row">
  <% @users.each do |user| %>
    <%= render 'epicenter/user', user: user %>
  <% end %>
</div>

app/views/epicenter/feed.html.erb
<div class="row">
  <div class="col-md-3">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= current_user.username %>'s Feed</h3>
      </div>
      <div class="panel-body">
        <%= pluralize current_user.tweets.count, 'tweet' %>
        <br />
        Following <%= pluralize current_user.following.count, 'tweety' %>
      </div>
    </div>

  </div>

  <div class="col-md-6">
    <%= render 'tweets/form', tweet: Tweet.new %>
    <% @following_tweets.each do |tweet| %>
      <%= render tweet %>
    <% end %>
  </div>

  <div class="col-md-3">

  </div>
</div>

app/views/epicenter/followers.html.erb
<h1><%= @user.username %>'s followers</h1>

<div class="row">
  <% @users.each do |user| %>
    <%= render 'epicenter/user', user: user %>
  <% end %>
</div>

app/views/epicenter/following.html.erb
<h1>Who <%= @user.username %> follows</h1>

<div class="row">
  <% @users.each do |user| %>
    <%= render 'epicenter/user', user: user %>
  <% end %>
</div>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>The profile of <%= @user.username %></h1>

<p>
  <strong>Name:</strong> <%= @user.name %>
</p>
<p>
  <strong>Location:</strong> <%= @user.location %>
</p>
<p>
  <strong>Bio:</strong> <%= @user.bio %>
</p>

<% if current_user.following.include?(@user.id) %>
  <%= link_to 'Following', unfollow_path(id: @user.id), id: 'unfollow_btn', class: 'btn btn-primary' %>
<% else %>
  <%= link_to 'Follow', now_following_path(id: @user.id), class: 'btn btn-primary' %>
<% end %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to 'Profile', show_user_path(id: @user.id) %>
  </li>
  <li>
    <%= link_to 'Following', following_path(id: @user.id) %>
  </li>
  <li>
    <%= link_to 'Followers', followers_path(id: @user.id) %>
  </li>
</ul>

<% @user.tweets.each do |tweet| %>
  <%= render tweet %>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %> tweets</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render @tag.tweets %>
  </div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Tweety', root_path, class: 'navbar-brand' %>
        </div>

        <ul class="nav navbar-nav">
          <li>
            <%= link_to 'All Users', all_users_path %>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.text_field :message, class: 'form-control', placeholder: 'What\'s happening?' %>
  </div>

  <div class="form-group">
    <%= form.submit nil, class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="well">
  <strong><%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %></strong> says...
  <div class="pull-right">
    <span class="glyphicon glyphicon-hourglass"></span>
    <% if tweet.created_at < 1.day.ago %>
      <%= tweet.created_at.strftime('%b %e') %>
    <% else %>
      <%= time_ago_in_words tweet.created_at %> ago
    <% end %>
  </div>
  <p>
    <%= tweet.message.html_safe %>
  </p>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user_id %></td>
        <td><%= tweet.message %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user_id) %>
</p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>